services:
    laravel.test:
        build:
            context: './vendor/laravel/sail/runtimes/8.5'
            dockerfile: Dockerfile
            args:
                WWWGROUP: '${WWWGROUP}'
        image: 'sail-8.5/app'
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        ports:
            - '${APP_BIND_HOST:-127.0.0.1}:${APP_PORT:-80}:80'
            - '${VITE_PORT:-5173}:${VITE_PORT:-5173}'
        environment:
            WWWUSER: '${WWWUSER}'
            LARAVEL_SAIL: 1
            XDEBUG_MODE: '${SAIL_XDEBUG_MODE:-off}'
            XDEBUG_CONFIG: '${SAIL_XDEBUG_CONFIG:-client_host=host.docker.internal}'
            IGNITION_LOCAL_SITES_PATH: '${PWD}'
        volumes:
            - '.:/var/www/html'
        networks:
            - sail
        depends_on:
            - mysql
            - redis
    mysql:
        image: 'mysql:8.4'
        ports:
            - '${FORWARD_DB_PORT:-3306}:3306'
        environment:
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ROOT_HOST: '%'
            MYSQL_DATABASE: '${DB_DATABASE}'
            MYSQL_USER: '${DB_USERNAME}'
            MYSQL_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ALLOW_EMPTY_PASSWORD: 1
            MYSQL_EXTRA_OPTIONS: '${MYSQL_EXTRA_OPTIONS:-}'
        volumes:
            - 'sail-mysql:/var/lib/mysql'
            - './vendor/laravel/sail/database/mysql/create-testing-database.sh:/docker-entrypoint-initdb.d/10-create-testing-database.sh'
        networks:
            - sail
        healthcheck:
            test:
                - CMD
                - mysqladmin
                - ping
                - '-p${DB_PASSWORD}'
            retries: 3
            timeout: 5s
    redis:
        image: 'redis:alpine'
        ports:
            - '${FORWARD_REDIS_PORT:-6379}:6379'
        volumes:
            - 'sail-redis:/data'
        networks:
            - sail
        healthcheck:
            test:
                - CMD
                - redis-cli
                - ping
            retries: 3
            timeout: 5s
    krakend:
        image: 'krakend:latest'
        profiles:
            - krakend
        ports:
            - '${KRAKEND_PORT:-8080}:8080'
            - '${KRAKEND_DEBUG_PORT:-8090}:8090'
            - '${KRAKEND_PROMETHEUS_PORT:-9091}:9091'
        command:
            - run
            - -d
            - -c
            - /etc/krakend/krakend.json
        volumes:
            - './docker/krakend/krakend.json:/etc/krakend/krakend.json:ro'
        networks:
            - sail
        depends_on:
            - laravel.test
    keycloak:
        image: 'quay.io/keycloak/keycloak:26.1'
        profiles:
            - krakend-auth
        command:
            - start-dev
            - --http-port=8080
            - --import-realm
        environment:
            KC_BOOTSTRAP_ADMIN_USERNAME: '${KEYCLOAK_ADMIN_USER:-admin}'
            KC_BOOTSTRAP_ADMIN_PASSWORD: '${KEYCLOAK_ADMIN_PASSWORD:-admin}'
        ports:
            - '${KEYCLOAK_PORT:-8085}:8080'
        volumes:
            - './docker/keycloak/realm-krakend.json:/opt/keycloak/data/import/realm-krakend.json:ro'
        networks:
            - sail
    rabbitmq:
        image: 'rabbitmq:3-management-alpine'
        profiles:
            - krakend-async
        ports:
            - '${RABBITMQ_PORT:-5672}:5672'
            - '${RABBITMQ_MANAGEMENT_PORT:-15672}:15672'
        networks:
            - sail
    jaeger:
        image: 'jaegertracing/all-in-one:latest'
        profiles:
            - krakend-observability
        ports:
            - '${JAEGER_UI_PORT:-16686}:16686'
            - '${JAEGER_OTLP_HTTP_PORT:-4318}:4318'
        networks:
            - sail
    influxdb:
        image: 'influxdb:1.8'
        profiles:
            - krakend-observability
        ports:
            - '${INFLUXDB_PORT:-8086}:8086'
        volumes:
            - 'sail-influxdb:/var/lib/influxdb'
        networks:
            - sail
    prometheus:
        image: 'prom/prometheus:v3.2.1'
        profiles:
            - krakend-observability
        ports:
            - '${PROMETHEUS_PORT:-9090}:9090'
        volumes:
            - './docker/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro'
            - './docker/prometheus/rules/krakend-alerts.yml:/etc/prometheus/rules/krakend-alerts.yml:ro'
            - 'sail-prometheus:/prometheus'
        networks:
            - sail
        depends_on:
            - krakend
    grafana:
        image: 'grafana/grafana:11.6.0'
        profiles:
            - krakend-observability
        environment:
            GF_SECURITY_ADMIN_USER: '${GRAFANA_ADMIN_USER:-admin}'
            GF_SECURITY_ADMIN_PASSWORD: '${GRAFANA_ADMIN_PASSWORD:-admin}'
        ports:
            - '${GRAFANA_PORT:-4000}:3000'
        volumes:
            - 'sail-grafana:/var/lib/grafana'
            - './docker/grafana/provisioning/datasources:/etc/grafana/provisioning/datasources:ro'
            - './docker/grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards:ro'
        networks:
            - sail
        depends_on:
            - influxdb
            - prometheus
networks:
    sail:
        driver: bridge
volumes:
    sail-mysql:
        driver: local
    sail-redis:
        driver: local
    sail-influxdb:
        driver: local
    sail-prometheus:
        driver: local
    sail-grafana:
        driver: local
