global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - /etc/prometheus/rules/krakend-alerts.yml

scrape_configs:
  - job_name: "krakend"
    metrics_path: /metrics
    static_configs:
      - targets:
          - "krakend:9091"
